<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQE9gaUU\symfonyTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQE9gaUU/symfonyTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQE9gaUU.legacy');

    return;
}

if (!\class_exists(symfonyTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQE9gaUU\symfonyTestDebugProjectContainer::class, symfonyTestDebugProjectContainer::class, false);
}

return new \ContainerQE9gaUU\symfonyTestDebugProjectContainer(array(
    'container.build_hash' => 'QE9gaUU',
    'container.build_id' => '31e6fa87',
    'container.build_time' => 1577992401,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQE9gaUU');
