<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWxnaoB\bootstrapTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWxnaoB/bootstrapTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGWxnaoB.legacy');

    return;
}

if (!\class_exists(bootstrapTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGWxnaoB\bootstrapTestDebugProjectContainer::class, bootstrapTestDebugProjectContainer::class, false);
}

return new \ContainerGWxnaoB\bootstrapTestDebugProjectContainer(array(
    'container.build_hash' => 'GWxnaoB',
    'container.build_id' => '4f0317d2',
    'container.build_time' => 1577990851,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWxnaoB');
